function skillsMember() {
    return [
        "C++",
        "Java",
        "Python",
        "C",
        "JavaScript",
        "HTML",
        "CSS",
        "SQL",
        "React",
        "Node.js",
        "Express",
        "MongoDB",
        "Firebase",
        "Git",
        "GitHub",
        "Heroku",
        "Netlify",
        "Vercel",
        "Docker",
        "Kubernetes",
        "Jenkins",
        "Travis CI",
        "Circle CI",
        "Jest",
        "Mocha",
        "Chai",
        "Cypress",
        "Jasmine",
        "Enzyme",
        "Puppeteer",
        "Selenium",
        "JIRA",
        "Confluence",
        "Trello",
        "Slack",
        "Discord",
        "Zoom",
        "Google Meet",
        "Microsoft Teams",
        "VS Code",
        "IntelliJ",
        "Eclipse",
        "PyCharm",
        "WebStorm",
        "Postman",
        "Swagger",
        "DBeaver",
        "DataGrip",
        "MySQL Workbench",
        "Xcode",
        "Android Studio",
        "Visual Studio",
        "Atom",
        "Sublime Text",
        "Vim",
        "Emacs",
        "Notepad++",
        "Windows",
        "macOS",
        "Linux",
        "iOS",
        "Android",
        "Windows Phone",
        "AWS",
        "Azure",
        "Google Cloud",
        "IBM Cloud",
        "Oracle Cloud",
        "Salesforce",
        "SAP",
        "ServiceNow",
        "Slack API",
        "Twilio API",
        "Stripe API",
        "PayPal API",
        "Facebook API",
        "Twitter API",
        "Google Maps API",
        "OpenStreetMap API",
        "Mapbox API",
        "Leaflet API",
        "Bootstrap",
        "Material-UI",
        "Ant Design",
        "Tailwind CSS",
        "Bulma",
        "Foundation",
        "Semantic UI",
        "UIKit",
        "Flutter",
        "React Native",
        "Xamarin",
        "Ionic",
        "PhoneGap",
        "Apache Cordova",
        "NativeScript",
        "Unity",
        "Unreal Engine",
        "Godot",
        "LÖ